language: swift
osx_image: xcode12.2

before_script: 
            - pod install
      


script:
   - xcodebuild test -workspace Instaframe.xcworkspace -scheme Instaframe -destination "platform=iOS Simulator,OS=14.2,name=iPhone 11 Pro" | xcpretty -s && exit ${PIPESTATUS[0]}
   
after_success:
  - bash <(curl -s https://codecov.io/bash)
