language: swift
osx_image: xcode12.2

env:
  matrix:
   - DESTINATION="platform=iOS Simulator,OS=14.2,name=iPhone 11 Pro"

before_script: pod install

script:
   - xcodebuild -quiet clean test -project Instaframe.xcworkspace -scheme Instaframe -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
   
after_success:
  - bash <(curl -s https://codecov.io/bash)
